FROM golang:1.14

# Install gRPC per https://grpc.io/docs/tutorials/basic/go/
# Install ginkgo and gomega per https://onsi.github.io/ginkgo/
RUN go get google.golang.org/grpc && \
    go get github.com/onsi/ginkgo/ginkgo && \
    go get github.com/onsi/gomega/...

# Copy over tests into GOPATH
WORKDIR /go/src/github.com/grpc/grpc-go/examples/route_guide
COPY . .

WORKDIR /go/src/github.com/grpc/grpc-go/examples/route_guide/bddTests
ENTRYPOINT [ "ginkgo", "-v"]
