version: "3.7"
services:
  route-server:
    build:
      context: .
      dockerfile: ./server/Dockerfile
    image: route-server:0.1
  route-client-bdd:
    build:
      context: .
      dockerfile: ./bdd_tests/Dockerfile.test
    image: route-client-bdd:0.1
    network_mode: service:route-server
